import AnimatedText from "@/components/AnimatedText";
import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import React, { useEffect, useRef } from "react";
import profileImage from "../../public/images/profile/developer-pic-2.jpg";
import { useInView, useMotionValue, useSpring } from "framer-motion";

const AnimatedNumber = ({ value }) => {
  const ref = useRef(null);

  const motionValue = useMotionValue(0);
  const springValue = useSpring(motionValue, { duration: 3000 });
  const isInView = useInView(ref, { once: true });

  useEffect(() => {
    if (isInView) {
      motionValue.set(value);
    }
  }, [isInView, value, motionValue]);

  useEffect(() => {
    springValue.on("change", (latest) => {
      if (ref.current && latest.toFixed(0) <= value) {
        ref.current.textContent = latest.toFixed(0);
      }
    });
  }, [springValue, value]);
  return <span ref={ref}></span>;
};

const about = () => {
  return (
    <>
      <Head>
        <title>Dev-Farhan | About</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex w-full flex-col items-center justify-center">
        <Layout className="pt-16">
          <AnimatedText text="Passion Fuels Purpose!" className="mb-16" />
          <div className="grid w-full grid-cols-8 gap-16">
            <div className="col-span-3 flex flex-col items-start justify-start">
              <h2 className="mb-4 text-lg font-bold uppercase text-dark/75">
                About Me
              </h2>
              <p className="font-medium">
                Hii, I'm Mohammad Farhan, a passionate and experienced MERN
                Stack Developer. With a strong foundation in MongoDB,
                Express.js, React, and Node.js, I specialize in building
                dynamic, high-performance web applications that deliver
                exceptional user experiences. My expertise lies in crafting
                seamless front-end interfaces and robust back-end architectures
                that drive modern, scalable solutions.
              </p>
              <p className="my-4 font-medium">
                I thrive in collaborative environments where innovation and
                creativity are at the forefront. My approach to development is
                driven by a commitment to clean code, best practices, and
                continuous learning. I am dedicated to staying updated with the
                latest industry trends and technologies to ensure that my
                projects are at the cutting edge of web development.
              </p>
              <p className="font-medium">
                Whether working on a team project or independently, I bring a
                detail-oriented mindset and problem-solving skills to every
                task. I am excited to contribute to challenging projects that
                push the boundaries of what's possible with the MERN stack.
                Let's connect and build something amazing together!
              </p>
            </div>
            <div className="col-span-3 relative h-max rounded-2xl border-2 border-solid border-dark bg-light p-8">
              <div className="absolute top-0 -right-3 -z-10 w-[102%] h-[103%] rounded-[2rem] bg-dark" />
              <Image
                src={profileImage}
                alt=""
                className="w-full h-auto rounded-2xl"
              />
            </div>
            <div className="col-span-2 flex flex-col items-end justify-between">
              <div className="flex flex-col items-end justify-center">
                <span className="inline-block text-7xl font-bold">
                  <AnimatedNumber value={10} />+
                </span>
                <h2 className="tex-xl font-medium capitalize text-dark">
                  Full Stack Projects
                </h2>
              </div>
              <div className="flex flex-col items-end justify-center">
                <span className="inline-block text-7xl font-bold">
                  {" "}
                  <AnimatedNumber value={10} />+
                </span>
                <h2 className="tex-xl font-medium capitalize text-dark">
                  Frontend Projects
                </h2>
              </div>
              <div className="flex flex-col items-end justify-center">
                <span className="inline-block text-7xl font-bold">
                  {" "}
                  <AnimatedNumber value={10} />+
                </span>
                <h2 className="tex-xl font-medium capitalize text-dark">
                  Backend Projects
                </h2>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
};

export default about;
